InvalidPluginConfigurationException: Create format string inline
Prefer to create format strings inline, instead of extracting them to a
single-use constant.

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: Ib2052b70183f3ca2594594a1554c0d292ff966e8